import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { GraphQlProvider } from "@/components/provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white dark:bg-slate-800 min-h-screen p-1">
          {
            <>
              <Header />
              <Toaster />
              <div className="container mx-auto py-2">
                <GraphQlProvider>{children}</GraphQlProvider>
              </div>
            </>
          }
        </div>
      </body>
    </html>
  );
}
